name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ubah sesuai dengan branch yang kamu gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Sesuaikan dengan versi yang kamu gunakan

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Build project
      - name: Build Project
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Sesuaikan dengan direktori hasil build
